openapi: 3.0.0
info:
  title: StackOverflow Clone
  description: StackOverflow is a platform for developers to learn from one another by asking questions and providing answers. This project is a mini clone of the actual StackOverflow at this site [https://stackoverflow.com/](https://stackoverflow.com/)

  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

externalDocs:
  description: Checkout the GitHub repo
  url: https://github.com/Ukhu/stack-overflow-clone

servers:
- url: /api/v1
  description: Local host

tags:
- name: Auth
  description: Authentication routes
- name: Question
  description: Question routes
- name: Answer
  description: Answer routes

security:
- ApiKeyAuth: []

paths:
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Sign up
      description: Creates a new user in the database
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: successfully created user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successfully created user!
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      displayName:
                        type: string
                      token:
                        type: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: object
                    properties:
                      body:
                        type: object
                        properties:
                          email:
                            type: string
                            example: must be a valid email
                          displayName:
                            type: string
                            example: displayName must be alphanumeric
        409:
          description: resource already exists
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
                    example: a user with the given email already exists
        500:
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
                    example: error occured!
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Logs in an existing user to the application
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: request successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: login successful!
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      displayName:
                        type: string
                      token:
                        type: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: object
                    properties:
                      body:
                        type: object
                        properties:
                          email:
                            type: string
                            example: must be a valid email
                          password:
                            type: string
                            example: password is required
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
                    example: email or password is incorrect
        500:
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
                    example: error occured!
  /questions:
    post:
      tags:
        - Question
      summary: Ask Question
      description: Creates a new question in the database
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        201:
          description: request successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successfully asked a question!
                  data:
                    type: object
                    properties:
                      _id: string
                      tags:
                        type: array
                        items:
                          type: string
                      owner: string
                      title: string
                      body: string
                      updatedAt: string
                      createdAt: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: object
                    properties:
                      body:
                        type: object
                        properties:
                          title:
                            type: string
                          body:
                            type: string
                          tags:
                            type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
        404:
          description: Entity not found
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string          
        500:
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
                    example: error occured!
  /questions/{questionId}/answers:
    post:
      tags:
        - Answer
      summary: Answer a question
      description: Creates an answer to a question in the database
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
      parameters:
        - name: questionId
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: request successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successfully answered a question!
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      owner:
                        type: string
                      body:
                        type: string
                      updatedAt:
                        type: string
                      createdAt:
                        type: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: object
                    properties:
                      body:
                        type: object
                        properties:
                          title:
                            type: string
                          body:
                            type: string
                          tags:
                            type: string

        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
        404:
          description: Entity not found
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
        500:
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
                    example: error occured!
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
